### ISSUE TITLE
review and complete the missing parts  in final srs 

### ISSUE THREAD

**Issue by menna2mohamed** [HaidySamir1696/SE2018G20#5]
menna ayman should review on introduction 
reham should review on description 
mona should review on user
esraa should review on modules
haidy should review on models 
nour el hoda should review on function req
rita should reivew  on domian req
salma should review on non function req
menna hussien should review on interface

**Comment by RitaEhab** [comment]
Reviewed! 
Data flow diagram should be edited.

**Comment by rehamashrafshouman** [comment]
Reviewed
Context diagram should be edited

**Comment by monaa12** [comment]
reviewed
